페이징 수정, 위치정보 요청 수정
boostcampwm-2021/android04-God-Fisherman pull request #110
Opened 2021-11-22 12:16 UTC by JeonJongHyeon97

### 이슈 번호✨

### PR 내용📢
- GPS상태 확인 코드 추가
- 위치 정보 Provider Network로 고정
- 페이징 관련 로딩 처리 수정

### 논의할 사항😥
-
-

2021-11-22 12:43 UTC, sejins commented on app/src/main/java/com/android04/godfisherman/ui/home/HomeViewModel.kt
> +    }
콜콜콜

2021-11-22 12:54 UTC, sejins commented on app/src/main/java/com/android04/godfisherman/utils/LocationHelper.kt
> +            showToast(context, "위치 센서 접근 불가")
토스트 내용을 `네트워크에 연결되지 않았습니다` 로 하는 건 어떤가요?

2021-11-22 14:47 UTC, potatoyum requested changes
`onCleared`는 없애는게 좋을 것 같아요🙃

2021-11-22 14:47 UTC, potatoyum commented on app/src/main/java/com/android04/godfisherman/ui/home/HomeViewModel.kt
> +    }
안 쓰는 메소드는 빼면 좋을 것 같아요!

2021-11-22 14:47 UTC, potatoyum commented on app/src/main/java/com/android04/godfisherman/utils/Extension.kt
> +}
내장된 `DateFormat`이나 `SimpleDateFormat`은 사용할 수 없나요??!

2021-11-23 00:53 UTC, JeonJongHyeon97 commented on app/src/main/java/com/android04/godfisherman/ui/home/HomeViewModel.kt
> +    }
아.. 깜빡했어요... 수정하겠습니다

2021-11-23 01:04 UTC, JeonJongHyeon97 commented on app/src/main/java/com/android04/godfisherman/utils/LocationHelper.kt
> +            showToast(context, "위치 센서 접근 불가")
이부분은 윤경님꺼랑 합치면서 수정될 부분이라, 할칠 때 반영하겠습니다.

2021-11-23 01:23 UTC, potatoyum approved these changes

2021-11-23 01:23 UTC, sejins approved these changes

2021-11-23 01:24 UTC, merged