버그 수정
boostcampwm-2021/android04-God-Fisherman pull request #111
Opened 2021-11-22 12:40 UTC by sejins

### 이슈 번호✨
- 낫띵

### PR 내용📢
- 타임라인 업로드 시 시간이 0으로 업로드 되는 이슈 해결
- 스톱워치화면 리사이클러뷰 아이템의 첫번째 갱신이 무시되는 이슈 해결\
- LoadingDialogProvider 생성
- 

### 논의할 사항😥
- 스톱워치를 종료하고 타임라인을 업로드 할 때도 사진 타입을 업로드할 때와 동일하게 다이얼로그를 사용할 것임
- 타임라인 데이터가 업로드가 완료되었다는 결과값이 오면 이에 맞게 다이얼로그를 on / off 하는 코드만 추가하면 됨
- 사진 타입 업로드 할 때와 타임라인 타입을 업로드할 때 모두 로딩 다이얼로그 뷰를 사용하기 위해 LoadingDialogProvider 생성

2021-11-22 14:28 UTC, potatoyum requested changes
`!!` 는 없애는게 좋을 것 같슴다

2021-11-22 14:28 UTC, potatoyum commented on app/src/main/java/com/android04/godfisherman/data/repository/HomeRepository.kt
> +    suspend fun fetchRankingList(num: Long): List<RankingData.HomeRankingData>
이건 왜 `Long`타입이어야 한가요?

2021-11-22 14:28 UTC, potatoyum commented on app/src/main/java/com/android04/godfisherman/ui/camera/upload/UploadActivity.kt
> -
함수 분리 좋아요👍

2021-11-22 14:28 UTC, potatoyum commented on app/src/main/java/com/android04/godfisherman/utils/RecyclerViewEmptySupport.kt
> +                this@RecyclerViewEmptySupport.visibility = View.VISIBLE
null인지 체크하고 있으니까 `!!`는 다 없애도 되지 않을까요?

2021-11-22 14:28 UTC, potatoyum commented on app/src/main/res/values/strings.xml
> +    <string name="welcome_help">오늘도 그물잠과 함께 낚시를 즐겨보세요!</string>
home에서만 쓰이니까 `home_`~ 이렇게 되어야 할 것 같아요

2021-11-22 14:31 UTC, sejins commented on app/src/main/java/com/android04/godfisherman/utils/RecyclerViewEmptySupport.kt
> +                this@RecyclerViewEmptySupport.visibility = View.VISIBLE
컴파일러가 인식을 못해요.. 그래서 if 문에서 nullable 하지 않은 것을 처리했기 때문에 ot null 단정자로 지정했습니다

2021-11-22 14:32 UTC, sejins commented on app/src/main/java/com/android04/godfisherman/data/repository/HomeRepository.kt
> +    suspend fun fetchRankingList(num: Long): List<RankingData.HomeRankingData>
파이어베이스 limit(num) 의 num 이 Long 타입이더라구요!

2021-11-22 14:33 UTC, sejins commented on app/src/main/res/values/strings.xml
> +    <string name="welcome_help">오늘도 그물잠과 함께 낚시를 즐겨보세요!</string>
아하 그렇게요 이건 수정할게요~!

2021-11-22 14:48 UTC, potatoyum commented on app/src/main/java/com/android04/godfisherman/utils/RecyclerViewEmptySupport.kt
> +                this@RecyclerViewEmptySupport.visibility = View.VISIBLE
?? 이거 코드 복붙해서 해봤는데 `!!` 떼라고 경고 뜨던데요?

2021-11-22 14:56 UTC, potatoyum commented on app/src/main/java/com/android04/godfisherman/utils/RecyclerViewEmptySupport.kt
> +                this@RecyclerViewEmptySupport.visibility = View.VISIBLE
아 이거 일반 변수가 아니었네요 ㅠ 그럼 어쩔 수 없는 것 같은데 방법을 찾아봐야겠어요

2021-11-23 00:52 UTC, JeonJongHyeon97 approved these changes

2021-11-23 01:28 UTC, potatoyum approved these changes

2021-11-23 01:47 UTC, merged